// noinspection JSUnusedGlobalSymbols

import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

export default {
  portfolio: [{type: 'autogenerated', dirName: 'portfolio'}],
  about: [{type: 'autogenerated', dirName: 'about'}],
  // 算法部分
  leetcode: [{type: 'autogenerated', dirName: 'algorithm/leetcode'}],
  dsa: [{type: 'autogenerated', dirName: 'algorithm/dsa'}],
  // 语言
  python: [{type: 'autogenerated', dirName: 'language/python'}],
  cpp: [{type: 'autogenerated', dirName: 'language/cpp'}],
  rust: [{type: 'autogenerated', dirName: 'language/rust'}],
  ts: [{type: 'autogenerated', dirName: 'language/ts'}],
  fundamentals_of_compiling: [{type: 'autogenerated', dirName: 'language/fundamentals_of_compiling'}],

  

  // cs部分
  computer_sciences: [{type: 'autogenerated', dirName:"cs/computer_sciences"}],
  database: [{type: 'autogenerated', dirName:"cs/database"}],
  os: [{type: 'autogenerated', dirName:"cs/os"}],
  software_industrials: [{type: 'autogenerated', dirName:"cs/software_industrials"}],
  web: [{type: 'autogenerated', dirName:"cs/web"}],
  //other
  math: [{type: 'autogenerated', dirName:"other/math"}],
  git: [{type: 'autogenerated', dirName:"other/git"}],
  tools: [{type: 'autogenerated', dirName:"other/tools"}],
  docker: [{type: 'autogenerated', dirName:"other/docker"}],


} satisfies SidebarsConfig;