// noinspection JSUnusedGlobalSymbols

import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

export default {
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
} satisfies SidebarsConfig;